/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms.ObraSocial;

import Datos.ObraSocial;
import Entidades.obraSocial;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Leo
 */
public class pnlComboObrasocial extends javax.swing.JPanel {
    private TreeMap<Integer, obraSocial> listobrasoc;
    private DefaultComboBoxModel modeloCombo;
    /**
     * Creates new form pnlComboObraSociales
     */
    public pnlComboObrasocial() {
        initComponents();
        _loadobrasoc();
    }
    
    private void _loadobrasoc(){
        ArrayList<obraSocial> list = new ArrayList<obraSocial>();
        ObraSocial cnx = new ObraSocial();
        if(cnx.isOkConexion()){
            list = cnx.listObraSocial("SELECT * FROM " + cnx.TABLA);
            cnx.isCloseConexion();
        }
        listobrasoc = new TreeMap<Integer, obraSocial>();
        modeloCombo = new DefaultComboBoxModel<String>();
        this.jComboBox.setModel(modeloCombo);
        for(int index=0;index<list.size();index++){
            obraSocial obraSocial = list.get(index);
            modeloCombo.addElement(obraSocial.getObrasocial().trim());
            listobrasoc.put(index, obraSocial);
        }
    }
    public obraSocial _getobrasocSelected(){
        return listobrasoc.get(jComboBox.getSelectedIndex());
    }
    
    public void _setobrasocSelected(int idobraSocial){
        int indexSelectedCombo = -1;
        for(int index=0;index<listobrasoc.size();index++){
            obraSocial obraSocial = listobrasoc.get(index);
            if(obraSocial.getId()==idobraSocial){
                indexSelectedCombo = index;
            }
        }
        jComboBox.setSelectedIndex(indexSelectedCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox = new javax.swing.JComboBox<>();
        btnobrasoc = new Botones.Btnobrasoc();
        btnactu = new Botones.Btnactu();

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnobrasoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnobrasoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnactu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactuActionPerformed
      _loadobrasoc();
    }//GEN-LAST:event_btnactuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Botones.Btnactu btnactu;
    private Botones.Btnobrasoc btnobrasoc;
    private javax.swing.JComboBox<String> jComboBox;
    // End of variables declaration//GEN-END:variables
}
