/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajofinal;

import forms.ObraSocial.FrmObraSocial;
import forms.especialidades.FrmEspecialidades;
import forms.pacientes.FrmPacient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import miselaneos.Fecha;
import miselaneos.GUI;
import miselaneos.Iconos;
import miselaneos.imagenes;

/**
 *
 * @author Usuario
 */
public class FrmSistema extends javax.swing.JFrame {

    public static Iconos iconos = new Iconos();
    public static imagenes img = new imagenes();
    public static Fecha fe = new Fecha();

    private GUI gui;

    /**
     * Creates new form FrmSistema
     */
    public FrmSistema() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        gui = new GUI();
    }

    private void _loadObrasocial() {
        gui.loadObrasocial(FrmObraSocial.id, true);
    }

    private void _loadPacient() {
        gui.loadPacient(FrmPacient.id, true);
    }

    private void _loadEspecialidades() {
        gui.loadEspecialidades(FrmEspecialidades.id, true);
    }

    private void SalirSistema() {
        if (JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema Por Completo.", "Atención!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDeskTopsistema = new miselaneos.JDeskTopsistema();
        jToolBarButtons = new javax.swing.JToolBar();
        btnEspecialidades1 = new Botones.BtnEspecialidades();
        btnObraSoc = new Botones.Btnloc();
        btncliente = new Botones.Btncliente();
        btnsalir = new Botones.Btnsalir();
        jMenuBar = new javax.swing.JMenuBar();
        Archivos = new javax.swing.JMenu();
        jMenuObra = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenuItem();
        jMenuEsp1 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Clinica(DEMO)");
        setIconImage(iconos.getSys(16).getImage());

        JDeskTopsistema.setPreferredSize(new java.awt.Dimension(1024, 800));
        getContentPane().add(JDeskTopsistema, java.awt.BorderLayout.CENTER);

        jToolBarButtons.setRollover(true);

        btnEspecialidades1.setFocusable(false);
        btnEspecialidades1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspecialidades1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspecialidades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialidades1ActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnEspecialidades1);

        btnObraSoc.setText("Obrasocial");
        btnObraSoc.setFocusable(false);
        btnObraSoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnObraSoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnObraSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObraSocActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnObraSoc);

        btncliente.setText("Pacientes");
        btncliente.setFocusable(false);
        btncliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btncliente);

        btnsalir.setFocusable(false);
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jToolBarButtons.add(btnsalir);

        getContentPane().add(jToolBarButtons, java.awt.BorderLayout.NORTH);

        Archivos.setText("Archivo");

        jMenuObra.setIcon(iconos.getEsp(16)
        );
        jMenuObra.setText("ObraSocial");
        jMenuObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuObraActionPerformed(evt);
            }
        });
        Archivos.add(jMenuObra);

        jMenuPacientes.setIcon(iconos.getClient(16)
        );
        jMenuPacientes.setText("Pacientes");
        jMenuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPacientesActionPerformed(evt);
            }
        });
        Archivos.add(jMenuPacientes);

        jMenuEsp1.setIcon(iconos.getEspecialidades(16)
        );
        jMenuEsp1.setText("Especialidades");
        jMenuEsp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEsp1ActionPerformed(evt);
            }
        });
        Archivos.add(jMenuEsp1);

        jMenuBar.add(Archivos);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jMenuItem3.setIcon(iconos.getExit(16)
        );
        jMenuItem3.setText("Salir del Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Salir.add(jMenuItem3);

        jMenuBar.add(Salir);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SalirSistema();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

    }//GEN-LAST:event_SalirActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        SalirSistema();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jMenuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPacientesActionPerformed
        _loadPacient();
    }//GEN-LAST:event_jMenuPacientesActionPerformed

    private void jMenuObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuObraActionPerformed
        _loadObrasocial();
    }//GEN-LAST:event_jMenuObraActionPerformed

    private void btnObraSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObraSocActionPerformed
        _loadObrasocial();
    }//GEN-LAST:event_btnObraSocActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        _loadPacient();
    }//GEN-LAST:event_btnclienteActionPerformed

    private void jMenuEsp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEsp1ActionPerformed
        _loadEspecialidades();
    }//GEN-LAST:event_jMenuEsp1ActionPerformed

    private void btnEspecialidades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialidades1ActionPerformed
        _loadEspecialidades();
    }//GEN-LAST:event_btnEspecialidades1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivos;
    public static miselaneos.JDeskTopsistema JDeskTopsistema;
    private javax.swing.JMenu Salir;
    private Botones.BtnEspecialidades btnEspecialidades1;
    private Botones.Btnloc btnObraSoc;
    private Botones.Btncliente btncliente;
    private Botones.Btnsalir btnsalir;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuEsp1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuObra;
    private javax.swing.JMenuItem jMenuPacientes;
    private javax.swing.JToolBar jToolBarButtons;
    // End of variables declaration//GEN-END:variables
}
