/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miselaneos;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import static trabajofinal.FrmSistema.iconos;
import static trabajofinal.FrmSistema.JDeskTopsistema;
/**
 *
 * @author Usuario
 */
public class FrmInterno extends javax.swing.JInternalFrame {

    
      private boolean isMem = false;
    /**
     * Creates new form FrmInterno
     */
    public FrmInterno() {
        initComponents();
    }
     public void _show(){
        Dimension deskTopSis = JDeskTopsistema.size();
        Dimension formInterno = getSize();
        
        if(!isMem){
            isMem = true;
            
            setSize(this.getWidth(), this.getHeight());
            
            setLocation((deskTopSis.width - formInterno.width) / 2,(deskTopSis.height - formInterno.height) / 2);
        }
        try{
            if(!isMaximumSizeSet()){
                setSelected(true);
                setIcon(false);
            }
            setVisible(true);
            moveToFront();
            toFront();
        }catch(PropertyVetoException ex){
            System.out.println("ERROR VENTANA INTERNA "+ '\n' + ex.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DEMO");
        setFrameIcon(iconos.getSys(16)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
